[tool.poetry]
name = "agenda-getter"
version = "0.1.0"
description = ""
authors = ["Jonathan O'Brien <jonathan@jonobri.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
pypdf = "^3.17.4"
selenium = "^4.16.0"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
